### ISSUE TITLE
Provide a Boundary Feature Service for joins

### ISSUE THREAD

**Issue by ajturner** [esridc/openfda#10]
Query by `where=State='OH'`

may already have one from the MyCongress App. document it.

**Comment by ajturner** [comment]
From @mhogeweg - http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Demographics/ESRI_Census_USA/MapServer

**Comment by mhogeweg** [comment]
sample query where: [state_abbr='OH'](http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Demographics/ESRI_Census_USA/MapServer/5/query?text=&geometry=&geometryType=esriGeometryPoint&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&objectIds=&where=STATE_ABBR%3D%27OH%27&time=&returnCountOnly=false&returnIdsOnly=false&returnGeometry=true&maxAllowableOffset=&outSR=&outFields=&f=html)

**Comment by benheb** [comment]
For now using http://services.arcgis.com/P3ePLMYs2RVChkJx/ArcGIS/rest/services/USA_States_Generalized/FeatureServer/0, with simple client-side agg. Closing this issue.
