### ISSUE TITLE
As Mary (Persona #1) I want to locate myself so that I only see food recalls that I'm interested in.

### ISSUE THREAD

**Issue by michaelgaigg** [esridc/openfda#11]
Location selection can be done by:
- clicking on the map
- typing a location in the search box (locator)
![uploads/bfede56b-fe97-4b23-a1b2-108cb665fa7e/Call to action.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbfede56b-fe97-4b23-a1b2-108cb665fa7e%2FCall+to+action.png)

**Comment by gclancy** [comment]
Interactions would be along the following lines:

- Mary navigates to recall web site (URL?)
- Mary enters City/State
- Mary enters key words for selected food e.g Lettuce, Ice Cream or ALL
