### ISSUE TITLE
As Mary (#1) I want to see a list of applicable food recalls so that I can take action and adjust our menu

### ISSUE THREAD

**Issue by michaelgaigg** [esridc/openfda#15]
![uploads/be25d4d2-a897-4e37-91eb-98f073be9b87/Recall list.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbe25d4d2-a897-4e37-91eb-98f073be9b87%2FRecall+list.png)

**Comment by gclancy** [comment]
![uploads/4d9fe421-7546-4658-99ed-f85fa7e8de4a/Phone - empty state.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4d9fe421-7546-4658-99ed-f85fa7e8de4a%2FPhone+-+empty+state.png)

**Comment by gclancy** [comment]
Recalls in Colorado:

Specific: https://api.fda.gov/food/enforcement.json?search=distribution_pattern=colorado&limit=100
Too many false returns: https://api.fda.gov/food/enforcement.json?search=distribution_pattern=CO&limit=100
