### ISSUE TITLE
As Mary I want to see details about a specific food recall so that I am well informed

### ISSUE THREAD

**Issue by michaelgaigg** [esridc/openfda#19]
Result is a list of recalls with as much detail as possible.

![uploads/f6abd998-c547-414e-8f9b-eb42c9fd77ae/Recall details.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff6abd998-c547-414e-8f9b-eb42c9fd77ae%2FRecall+details.png)

**Comment by ajturner** [comment]
Please split this up into two stories
