### ISSUE TITLE
As Mary, i want to be able to send a recall notice that I have received with my friends, so that they can be informed and make better decisions.

### ISSUE THREAD

**Issue by gclancy** [esridc/openfda#20]
Mary receives an alert on her phone and thinks that her neighbor (Jane) would be interested in knowing about it.

**Comment by michaelgaigg** [comment]
Related to #22

This user story has an impediment from the business side. The API documentation for the food enforcement reports (https://open.fda.gov/food/enforcement/reference/) states: "This data should not be used as a method to collect data to issue alerts to the public, nor should it be used to track the lifecycle of a recall."
My interpretation is that the application should not allow subscription to alerts and therefore block this user need. 
Alternatively a link to a site (need research) that allows subscriptions of that kind could be added.

**Comment by ajturner** [comment]
we can't do "notifications" , but we can do "Share" like as an Email or Post to Facebook

**Comment by gclancy** [comment]
Determined that this requested feature was not supported by the FDA API.  Remove from backlog and close
