### ISSUE TITLE
As Mary, I want to set up notifications for recalls I am interested in so that I receive automated updates without the need to come back to the site all the time

### ISSUE THREAD

**Issue by gclancy** [esridc/openfda#22]

**Comment by gclancy** [comment]
Interaction along the following lines:

- Mary navigates to the recall site (URL?)
- Mary enters key words for selected food e.g Lettuce, Ice Cream or ALL

**Comment by michaelgaigg** [comment]
This user story has an impediment from the business side. The API documentation for the food enforcement reports (https://open.fda.gov/food/enforcement/reference/) states: "This data should not be used as a method to collect data to issue alerts to the public, nor should it be used to track the lifecycle of a recall."
My interpretation is that the application should not allow subscription to alerts and therefore block this user need. 
Alternatively a link to a site (need research) that allows subscriptions of that kind could be added.

**Comment by gclancy** [comment]
Determined that API does not support this request.  Remove from backlog and close
