### ISSUE TITLE
Usability Test 1:  Persona test with Mary - Manager of Food Services for a chain of hospitals in Arizona

### ISSUE THREAD

**Issue by gclancy** [esridc/openfda#24]
Usability test:  Have employee play the role of Mary - Manger of Food Services for a chain of Hospitals in Arizona.  

Reassure them that there is no right/wrong answer - looking for their feedback and comments.

- show them a paper copy of the wire frame and watch their interaction and report.  can they answer the question "What recalls have been made recently by FDA for my state"

**Comment by gclancy** [comment]
Observations from usability test:

Felt satisfied that they could answer question posed.  However a number of frustrations:

- how did i set that my area of interest was Arizona?  
- what is the drill-in perspective if I click on one of the categories. e.g. clicking on “4 Dangerous or defective” seems like it should show me those 4 as a list of food type & recency.  Really would like to see as much detail as possible on these....
- what is the next step if i see a recall that I need more information on - what do i do?  
- concerned that its going to get me all worried about a recall but will not know what to do next.
- the colors seem a bit odd....would a red, yellow, green color pattern be more effective?
- would like to see today's date on the top (not just "..Last 7 days..."

**Comment by ajturner** [comment]
Thanks for sharing! These are great insights and I'm looking forward to the updated mocks.

can you document the questions posed? and provide a link to the Wiki with the mocks that were tested and these summarized notes?

**Comment by michaelgaigg** [comment]
https://github.com/esridc/openfda/wiki/WireframesIteration1

**Comment by michaelgaigg** [comment]
Recommendations from UX team:
- Clearly label pages (e.g. recall list) DONE
- Provide a mechanism to navigate back, i.e. after selecting a state, how does a user show the National map again?
- Make 'dashboard' boxes clickable so that they serve as navigation (navigate to recall list) + filter selection (on class)
- Color the boxes with a common color scheme that represents high/medium/low danger (typically red/orange/yellow)
