### ISSUE TITLE
Set up back end technology stack to support prototype

### ISSUE THREAD

**Issue by gclancy** [esridc/openfda#27]
Get running in Docker on Amazon Container Services
- [x] Get docker contains running locally and working together
- [x] Host image on Docker Hub [link](https://registry.hub.docker.com/u/dmfenton/koop-docker-example/)
- [x] Deploy onto AWS

**Comment by dmfenton** [comment]
Access koop on Docker here: koop-fda-1504637322.us-east-1.elb.amazonaws.com
