### ISSUE TITLE
As Dr. Bob, I would like to see the origination of recalled products, in order to identify trends 

### ISSUE THREAD

**Issue by jodimward** [esridc/openfda#28]

**Comment by ajturner** [comment]
![uploads/850ad030-e7dc-4b55-aed9-097b3057b40c/Screenshot_6_26_15__1_13_PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F850ad030-e7dc-4b55-aed9-097b3057b40c%2FScreenshot_6_26_15__1_13_PM.png)
