### ISSUE TITLE
As Mary I want to be able to navigate the application on my mobile device (phone) because I don't have time to go upstairs and boot up my desktop computer

### ISSUE THREAD

**Issue by michaelgaigg** [esridc/openfda#33]
![uploads/b56002fb-9e77-4b99-9f84-21c0bd85d3aa/Phone - empty state.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb56002fb-9e77-4b99-9f84-21c0bd85d3aa%2FPhone+-+empty+state.png)

**Comment by benheb** [comment]
Closing this story as Mary can visit the app on a mobile device without any issues. Final design looks a little different than the mocks above as we decided to build the mobile experience purely off of responsive design, while the mocks would have required slightly different mockup. 

Mobile will look very similar to desktop with a few differences: 
* No download option on mobile devices 
* No home screen chart, just map view 
* Search and lists take up 100% width for a more typical mobile-feel. 

![img_2562](https://cloud.githubusercontent.com/assets/910495/8440578/500cd704-1f30-11e5-835a-5695eec3a44a.jpg)

![img_2561](https://cloud.githubusercontent.com/assets/910495/8440579/54a13558-1f30-11e5-9187-c69aa2e863ad.jpg)
