### ISSUE TITLE
As Dr. Bob, I would like to have the ability to visualize recalls by state in a bar chart

### ISSUE THREAD

**Issue by jodimward** [esridc/openfda#37]
Only show the top 15 states by count.

similar to:
 
![uploads/b00eb2f3-9d6d-432a-b947-d13861f33e6f/Screenshot_6_26_15__1_15_PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb00eb2f3-9d6d-432a-b947-d13861f33e6f%2FScreenshot_6_26_15__1_15_PM.png)

**Comment by michaelgaigg** [comment]
![uploads/db22ae56-c384-4a85-861a-40bba7f741de/Empty state.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fdb22ae56-c384-4a85-861a-40bba7f741de%2FEmpty+state.png)

**Comment by michaelgaigg** [comment]
- The decision has been made that the chart will show all states (instead only Top 10) which seems to be more beneficial to a user. Further validation from the user is recommended.

- Display options will be moved to it's own work item
