### ISSUE TITLE
I'm a manager of food quality in my school districts and need to be aware of food recalls that affect my district

### ISSUE THREAD

**Issue by mhogeweg** [esridc/openfda#4]
Proposed workflow

- User is asked to type in a Zipcode (or other geography)
- User sees a list of Food Recalls
- User can 'subscribe' to the results as a Feed (GeoRSS)
- Provide resources for user to respond [see Response PDF](http://www.fns.usda.gov/sites/default/files/Responding_Food_Recall_FNS_Final_May_30_2014.pdf)

receive notification of new recalls or lifted recalls
limit by geography (my school district)
how does school official respond? notify schools?

**Comment by mhogeweg** [comment]
see: http://www.fns.usda.gov/sites/default/files/Responding_Food_Recall_FNS_Final_May_30_2014.pdf

**Comment by ajturner** [comment]
Recalls in Colorado: 

Specific: https://api.fda.gov/food/enforcement.json?search=distribution_pattern=colorado&limit=100
Too many false returns: https://api.fda.gov/food/enforcement.json?search=distribution_pattern=CO&limit=100

**Comment by gclancy** [comment]
Not going to implement this use case - decided to pursue different personas
