### ISSUE TITLE
Internal review with Esri staff that have experience in health and safety

### ISSUE THREAD

**Issue by gclancy** [esridc/openfda#41]
Review the current wire-frames with Esri staff that have experience in the Heath and Safety Industry.  

- is this an appropriate use of the FDA data - is this what they need?
- how would users typically use this data
- do the personas we have identified make sense
- how would they navigate the app - is it simple and intuitive?
- what additional data would be needed to add value ?

**Comment by michaelgaigg** [comment]
I'm not exactly sure how these comments can be turned into useful action items.

**Comment by gclancy** [comment]
I showed the Esri Health Director the latest working prototype and obtained the following comments & feedback. 

- liked the overall feel of the app and how the data comes alive - rather then seeing everything as a long list of items on a spreadsheet.

comments on how to improve:

- interesting way to view the data...but want to see more - any data below the state level?
need to be able filter on date, most users would really only want to see recent or current recalls.
-  Dr Bob probably wants to see more trends and would probably like more time series approach to the visualization..
- probably important to add other data to the visualization.  For example, a simple chart that shows total population impacted would help cement the focus for end users.  A recall affecting 10 states - different impact if those ten states are the most populous ones.
- this type of visualization would let end users - particularly someone like a public health worker begin to focus their limited resources.
- need to change the name - GSA 18F prototype not going to resonate!  Change to something like  "Mapping FDA Food Recalls Across the Nation"

**Comment by gclancy** [comment]
Mike - can you review the comments above and see how we can address in new wireframes

**Comment by michaelgaigg** [comment]
Thanks for the additional information. I believe that showing trends would be extremely useful not only to Dr. Bob but also to Mary, i.e. to see which states have had increases in recall volume over the past 3 consecutive years. I think further research needs to be taken to establish a true needs analysis so that we can settle and decide on a true user need and thus make it a requirement (user story).

**Comment by gclancy** [comment]
Excellent - population impact added to the bottom of the recall window!!  Works great and gives real integration with external data set.  Would definitely help the user to better understand impact - well done!

![image](https://cloud.githubusercontent.com/assets/13022624/8420313/1513d1d0-1e8f-11e5-95f6-5a9bad0f2948.png)

**Comment by michaelgaigg** [comment]
Agree! PR merged.. ☺

**Comment by dmfenton** [comment]
This has been completed closing the issue.
