### ISSUE TITLE
UX Recommendations/Comments based on Usability Testing

### ISSUE THREAD

**Issue by michaelgaigg** [esridc/openfda#44]
Today (Thursday) we conducted 3 usability tests based on the wireframes. Details can be seen on #24, #39, #40 (and some more feedback on #41). 

Based on theses insights the UX team recommends considering the following:
- [x] Clearly label pages (e.g. recall list)
- [x] Provide a mechanism to navigate back, i.e. after selecting a state, how does a user show the National map again?
- [ ] ~~Make 'dashboard' boxes clickable so that they serve as navigation (navigate to recall list) + filter selection (on class)~~
- [ ] ~~Color the boxes with a common color scheme that represents high/medium/low danger (typically red/orange/yellow)~~
- [x] Consider changing the tagline to "Find recalled products in your state"
- [x] Use neutral cartographic symbology (e.g. blue) so that a selected state isn't mistaken as dangerous (if it was orange)
- [x] Highlight recalls that are new (e.g. within the last week) so that a user that is following the listing closely can easily identify the new ones
- [ ] ~~Subscribe to feed function (or label) wasn't clear. Questioning whether users would be familiar with this concept~~ (we don't have subscribe)
- [x] Question to dev team: is there a way to state whether a recall affects retail or wholesale? This would be important to know for Mary (not a field in the API results - Brendan) 
- [x] Eliminate confusing / conflicting data; possibly change labels or representation or question whether to show in the first place? (What does this mean? - Brendan) 
- [x] Filter for recall data based on date appears to be of importance to the user
- [x] General comment about the map after selecting a state: Is there anything useful that can be displayed (when in list view; when in details view)?

**Comment by ajturner** [comment]
@michaelgaigg is going to provide a UI update for @benheb to then implement

**Comment by michaelgaigg** [comment]
![uploads/f3b8724c-e013-406c-b9d6-23543171c554/Recall list.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff3b8724c-e013-406c-b9d6-23543171c554%2FRecall+list.png)

![uploads/6abb966e-1bea-4a10-801a-3bd7f5e21ebf/Recall details.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6abb966e-1bea-4a10-801a-3bd7f5e21ebf%2FRecall+details.png)

**Comment by benheb** [comment]
@ajturner @gclancy @michaelgaigg I've checked the boxes that are done, and crossed out those that can't be done, or aren't relevant anymore. A few I have questions on... If anyone has the answers.

**Comment by michaelgaigg** [comment]
Everything looks good. 

The comment about confusing labels was a general one and seems to be addressed in latest release.

Having the extent stay at national level and showing originating state with arcs to affected states on hover of a recall now satisfies the "map not being useful"
