### ISSUE TITLE
User can filter recalls by number of days

### ISSUE THREAD

**Issue by ajturner** [esridc/openfda#49]
![uploads/be25d4d2-a897-4e37-91eb-98f073be9b87/Recall list.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbe25d4d2-a897-4e37-91eb-98f073be9b87%2FRecall+list.png)

**Comment by ajturner** [comment]
question for @dmfenton can you verify if there are data within last 7 days or 30 days. or if we go to last 6 months, last year, last 5 years.

**Comment by michaelgaigg** [comment]
I agree, let's have some meaningful options in this dropdown

**Comment by dmfenton** [comment]
Here's the breakdown:
![image](https://cloud.githubusercontent.com/assets/7832202/8412411/c65debd4-1e57-11e5-9c26-c25fed41cc9c.png)
