### ISSUE TITLE
User can "change state" to see the national view

### ISSUE THREAD

**Issue by ajturner** [esridc/openfda#50]
![uploads/be25d4d2-a897-4e37-91eb-98f073be9b87/Recall list.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbe25d4d2-a897-4e37-91eb-98f073be9b87%2FRecall+list.png)

**Comment by benheb** [comment]
@ajturner @michaelgaigg So I deviated from the mocks a little here, and am wondering if this capability still makes sense. Currently when a user searches or clicks on a state, we don't zoom to that state. This is so the list hovers (showing source state) can show up at the national view. Also the search box is not hidden after a state selection is made. So unless I change this, what would the action 'change state' do at this point? I believe we agreed in a PR yesterday that we weren't going to zoom in to state on select. 

![open_fda](https://cloud.githubusercontent.com/assets/910495/8385131/3115fe8c-1c03-11e5-8075-cf8932a6dfc3.jpg)

**Comment by ajturner** [comment]
Users need to be able to 'reset' to home. 

Or why remove the choropleth and instead just put a white border (or similar) around the selected state?

**Comment by benheb** [comment]
Just seemed too busy with choropleth and not relevant want entering into state view. I'll add a button to go home.
