### ISSUE TITLE
did we loose the different colors associated with the 3 types of recalls?  red, orange, yellow?

### ISSUE THREAD

**Issue by gclancy** [esridc/openfda#56]
![image](https://cloud.githubusercontent.com/assets/13022624/8387425/4b80b24e-1c26-11e5-80b3-202bd01e8055.png)

**Comment by michaelgaigg** [comment]
the 3 colors were primarily meant to appear on the "dashboard" that is part of the info window - which has been deprecated. Since this info window doesn't appear anymore we don't really need that continuation on the tabs.
