### ISSUE TITLE
Decide on openFDA consuming technology

### ISSUE THREAD

**Issue by mhogeweg** [esridc/openfda#6]
We have 3 options for consuming the data from openFDA
- regular ETL into geodatabase ahead of time
- use koop to geoenable the openFDA during request time
- develop client-side interaction

we need to quickly decide on the approach.

**Comment by michaelgaigg** [comment]
In progress - under investigation

**Comment by ajturner** [comment]
We are using [Koop](https://github.com/esri/koop) since the _requirements_ state that Container technology is required. This will spatially-enable the openFDA API.
