### ISSUE TITLE
issue with search tool after geocode

### ISSUE THREAD

**Issue by gclancy** [esridc/openfda#66]
Process to reproduce:

type in address in search window

when it redraws the search window does not refresh - but is scaled back.

Also Search results indicate "undefined" rather then the address....

![image](https://cloud.githubusercontent.com/assets/13022624/8420239/5ca68a84-1e8e-11e5-9257-46333840f4db.png)

**Comment by benheb** [comment]
@gclancy what address are you searching? I can't seem to replicate.

**Comment by gclancy** [comment]
1822 calvert st nw, Washington DC

Also saw it just when you type in a city like Chicago.

Gerry


Sent from my Verizon Wireless 4G LTE Smartphone


-------- Original message --------
From: Brendan Heberton
Date:06/29/2015 7:54 PM (GMT-05:00)
To: esridc/openfda
Cc: Gerry Clancy
Subject: Re: [openfda] issue with search tool after geocode (#66)


@gclancy<https://github.com/gclancy> what address are you searching? I can't seem to replicate.

**Comment by benheb** [comment]
Ok I see it with DC, but not Chicago. Issue with DC is the states Feature Service I am using apparently doesn't have DC... http://services.arcgis.com/P3ePLMYs2RVChkJx/ArcGIS/rest/services/USA_States_Generalized/FeatureServer/0

Either will just be a known issue, or I may need help tracking down a feature service that has DC, and all the same stats as this one (state abbr, census data).

**Comment by gclancy** [comment]
Ah - I do not think we will be able to find a different layer with all the same info.  Can we make sure to log this as an issue with the ArcGIS Online team.

**Comment by dmfenton** [comment]
Looks like that feature service does contain DC, so I'm not sure what the fix is here from me. @benheb can you take another look?

![arcgis_-_my_map](https://cloud.githubusercontent.com/assets/7832202/8454095/a2af866c-1fc8-11e5-8ca9-2fa950c60afe.jpg)

**Comment by benheb** [comment]
Yep, I see the issue. PR in a few min.
