### ISSUE TITLE
Dots on map dont change and are confusing

### ISSUE THREAD

**Issue by dmfenton** [esridc/openfda#68]
STR
1. visit the prototype http://esridc.github.io/openfda/
observe blue dots on the map
2. click on any states
observe the dots don't change.

Maybe I'm just missing the point of these dots, but it's confusing that there's no interaction and they don't change.
![dots](https://cloud.githubusercontent.com/assets/7832202/8430835/9351dd76-1f02-11e5-8eab-b9af6b4e7a98.gif)

**Comment by gclancy** [comment]
Daniel - can you post an image of what you are seeing - "observe blue dots"  i do not see those..

**Comment by dmfenton** [comment]
added gif, sorry meant to attach that originally

**Comment by gclancy** [comment]
Ah - looks like the original dot on the Florida recall is not getting cleared....the blue dots should only show when you are hovering over the recall list....

**Comment by benheb** [comment]
@dmfenton are you still observing this this morning? May be fixed, but I can't seem to replicate. How do what are the steps leading up to getting the blue dots to get stuck on the map?

**Comment by dmfenton** [comment]
Looks like it is fixed. Going to close
