### ISSUE TITLE
Loading spinner overlaps Esri Logo

### ISSUE THREAD

**Issue by slibby** [esridc/openfda#73]
When loading the map, the loading spinner (pretty!) overlaps the Esri logo (not pretty!)

![image](https://cloud.githubusercontent.com/assets/1691225/8439209/808683c8-1f38-11e5-9fc4-04f523d88f70.png)

**Comment by benheb** [comment]
Resolved in PR https://github.com/esridc/openfda/pull/72 

![gsa_18f_prototype](https://cloud.githubusercontent.com/assets/910495/8440709/42954e48-1f31-11e5-88f8-0df7805d4de7.jpg)
