### ISSUE TITLE
Android testing 

### ISSUE THREAD

**Issue by gclancy** [esridc/openfda#74]
i found the following issues on testing an Samsung Galaxy running Android.

- [x] Back to Overview does not work: the map does not display and the screen is in affect frozen
- [x] the download button is on the screen and makes the call to KOOP and does complete the download.  The Download button should be removed.
- [x]  population numbers are not formatted correctly

**Comment by benheb** [comment]
I've got a fix for the numeric formatting PR'd (ready for merge https://github.com/esridc/openfda/pull/75), and the download option should be now removed from mobile view. The first one is harder since I don't have an android to test with...

**Comment by gclancy** [comment]
- [ ] back to over view did not work for me on android or iOS
- [ ] population numbers did not seem to be formatted on android or iOS

confirmed - download button is gone - excellent

**Comment by benheb** [comment]
Should all work now. No chart on mobile, so back to overview should take you back to same map seen when first loading app.
