### ISSUE TITLE
Mobile - hiding the list view then clicking on a state throws a JS error

### ISSUE THREAD

**Issue by ajturner** [esridc/openfda#80]
- View in Chrome Device mode a small screen
- Type in `20002` for location
- click the `x` to hide the panel
- click on a state

error: `TypeError: cannot read property results of undefined`

**Comment by benheb** [comment]
@ajturner can you gif me? I can't replicate locally or on gh-pages.

**Comment by gclancy** [comment]
I tried on Chome on laptop and could not duplicate.

I do however see the search window collapse and not expand after the query is executed…

[cid:image001.png@01D0B7EF.6801CE80]

**Comment by benheb** [comment]
Unable to replicate issue. Closing.
