### ISSUE TITLE
Import Koop-OpenFDA as a directory of this project

### ISSUE THREAD

**Issue by ajturner** [esridc/openfda#82]
In compliance with  Question 16 of the Technical Q&A everything developed for this project should be in one repository.

Therefore - add the entire [openfda-koop](https://github.com/esridc/openfda-koop) project as a directory in this project and refer to that in README and Dockerfile.

This would _not_ be how one typically releases software, opting instead for separate repositories for components.

**Comment by dmfenton** [comment]
Should we just handle the docker file in here? Or should I move the provider as well?

**Comment by ajturner** [comment]
Purely for RFQ conformance - put the entire provider here.

we can still leave Koop itself outside - as that is an 'openly licensed, independent modern web technology' we used.

**Comment by dmfenton** [comment]
Done
