### ISSUE TITLE
Investigate Cloudwatch for monitoring External URL

### ISSUE THREAD

**Issue by ajturner** [esridc/openfda#83]

**Comment by dmfenton** [comment]
Setting up using http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-failover-determining-health-of-endpoints.html

**Comment by dmfenton** [comment]
Up and running
![image](https://cloud.githubusercontent.com/assets/7832202/8529570/50fb6fdc-23e9-11e5-965c-564738dbc511.png)

**Comment by ajturner** [comment]
@dmfenton can this to and HTML dom detection? 

what if the front-page were "blank"?

**Comment by dmfenton** [comment]
yes, we can do dom matching. But not sure that's going to catch a JS error which will likely cause the blank screen.
